version: '3.8'

services:
  postgres:
    container_name: postgres-dns-movies
    image: postgres:15.2
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./data:/var/lib/docker/volumes/
    ports:
      - ${POSTGRES_PORT_OUTSIDE}:${POSTGRES_PORT_INSIDE}

  rabbitmq:
    container_name: pabbitmq-dns-movies
    image: rabbitmq
    env_file:
      - ./.env
    ports:
      - ${RABBITMQ_PORT_OUTSIDE}:${RABBITMQ_PORT_INSIDE}