version: '3.8'

services:

  postgres:
    container_name: postgres-testing
    image: postgres:15.2
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./initdb-scripts/testdb:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_PORT_OUTSIDE}:${POSTGRES_PORT_INSIDE}

  rabbitmq:
    container_name: rabbitmq-dns-movies
    image: rabbitmq
    hostname: rabbitmq
    restart: always
    env_file:
      - ./.env
    ports:
      - ${RABBITMQ_PORT_OUTSIDE}:${RABBITMQ_PORT_INSIDE}

  auth:
    container_name: auth-dns-movies
    build:
      dockerfile: ./server/auth/Dockerfile
      context: ./
    env_file:
      - ./.env
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./server/auth:/app/server/auth
      - /app/server/auth/node_modules
