version: '3.8'

services:

  postgres:
    container_name: postgres-dns-movies
    image: postgres:15.2
    restart: always
    profiles:
      - dev
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_PORT_OUTSIDE}:${POSTGRES_PORT_INSIDE}

  postgres_test:
    container_name: postgres-dns-movies-test
    image: postgres:15.2
    restart: always
    profiles:
      - test
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    hostname: postgres
    volumes:
      - ./initdb-scripts/testdb:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_PORT_OUTSIDE}:${POSTGRES_PORT_INSIDE}

  rabbitmq:
    container_name: rabbitmq-dns-movies
    image: rabbitmq
    hostname: rabbitmq
    restart: always
    env_file:
      - ./.env
    ports:
      - ${RABBITMQ_PORT_OUTSIDE}:${RABBITMQ_PORT_INSIDE}

  auth:
    container_name: auth-dns-movies
    build:
      dockerfile: ./server/auth/Dockerfile
      context: ./
    env_file:
      - ./.env
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./server/auth:/app/server/auth
      - /app/server/auth/node_modules

  social:
    container_name: social-dns-movies
    build:
      dockerfile: ./server/social/Dockerfile
      context: ./
    env_file:
      - ./.env
    depends_on:
      - postgres
      - rabbitmq
      - auth
    volumes:
      - ./server/social:/app/server/social
      - /app/server/social/node_modules

  persons:
    container_name: persons-dns-movies
    build:
      dockerfile: ./server/persons/Dockerfile
      context: ./
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - ./server/persons:/app/server/persons
      - /app/server/persons/node_modules

  movies:
    container_name: movies-dns-movies
    build:
      dockerfile: ./server/movies/Dockerfile
      context: ./
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - ./server/movies:/app/server/movies
      - /app/server/movies/node_modules

  api:
    container_name: api-dns-movies
    build:
      dockerfile: ./server/api/Dockerfile
      context: ./
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
      - persons
      - movies
      - auth
      - social
    volumes:
      - ./server/api:/app/server/api
      - /app/server/api/node_modules
    ports:
      - ${API_GATEWAY_PORT}:3000
